name: Build Flet APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Aumentamos recursos (opcional en runners públicos, pero ayuda)
    env:
      FLUTTER_ROOT: ${{ github.workspace }}/flutter

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Flutter (versión compatible)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # Versión más estable para Flet
          channel: 'stable'

      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses > /dev/null 2>&1 || true

      - name: Install Flet (versión probada)
        run: pip install flet==0.23.1

      - name: Build APK
        run: flet build apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: build/apk/*.apk
