name: Build Flet APK

on:
  workflow_dispatch:  # Se ejecuta manualmente desde GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar tu código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Configurar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      # 4. Instalar dependencias necesarias (Java, licencias Android, Flet)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          yes | flutter doctor --android-licenses
          pip install flet==0.23.1

      # 5. Compilar la app como APK
      - name: Build APK
        run: flet build apk

      # 6. Subir el APK generado como artefacto
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: build/apk/*.apk
          
