name: Build Flet APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          yes | flutter doctor --android-licenses
          pip install flet==0.23.1

      - name: Build APK
        run: flet build apk --module-name main
        env:
          ANDROID_COMPILE_SDK: 35
          ANDROID_BUILD_TOOLS_VERSION: 35.0.0

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: build/apk/*.apk
          
