name: Build Flet APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet
        run: pip install flet

      - name: Build APK
        run: flet build apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: build/apk/*.apk
